# Generated by Django 4.0.4 on 2022-06-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialties',
            new_name='Specialty',
        ),
    ]
