# Generated by Django 4.0.4 on 2022-06-06 18:00

import apps.specialties.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtiesdoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialties', to=settings.AUTH_USER_MODEL, validators=[apps.specialties.models.SpecialtiesDoctor.is_doctor]),
        ),
        migrations.AddField(
            model_name='specialtiesdoctor',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties_doctor', to='specialties.specialty'),
        ),
    ]
