# Generated by Django 4.0.4 on 2022-06-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0002_rename_specialties_specialty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialty',
            new_name='Speciality',
        ),
    ]
