# Generated by Django 4.0.4 on 2022-06-04 18:07

import apps.specialties.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialties', '0004_alter_specialtiesdoctor_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtiesdoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialties', to=settings.AUTH_USER_MODEL, validators=[apps.specialties.models.SpecialtiesDoctor.is_doctor]),
        ),
    ]
