version: '3'

services:
  postgres:
    restart: always
    image: postgres:13
    container_name: postgres_ap
    ports:
      - "5432:5432"
    volumes:
      - .data/:/tmp
    env_file:
      - .env

  web:
    restart: always
    build:
      context: .
    volumes:
      - .:/src
    env_file:
      - .env
    command: >
      sh -c "python manage.py test && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - postgres
