# Generated by Django 4.0.4 on 2022-06-04 15:34

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='names',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Patient'), (2, 'Doctor')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
