# Generated by Django 4.0.4 on 2022-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers_remove_user_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_tuition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
