# Generated by Django 4.0.4 on 2022-06-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_birth_date_alter_user_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
