# Generated by Django 4.0.4 on 2022-06-04 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dates',
            new_name='Date',
        ),
        migrations.RenameModel(
            old_name='Schedules',
            new_name='Schedule',
        ),
    ]
