# Generated by Django 4.0.4 on 2022-06-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
