# Generated by Django 4.0.4 on 2022-06-04 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dates', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_date', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='date',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_date', to=settings.AUTH_USER_MODEL),
        ),
    ]
