# Generated by Django 4.0.4 on 2022-06-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0005_date_patient_alter_date_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='atention_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='date',
            name='atention_start',
            field=models.TimeField(),
        ),
    ]
