# Generated by Django 4.0.4 on 2022-06-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0006_alter_date_atention_end_alter_date_atention_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='atention_date',
            field=models.DateField(),
        ),
    ]
